### ISSUE TITLE
Toolkit done with?

### ISSUE THREAD

**Issue by tasdikrahman** [prodicus/thanos#2]
We have successfully addressed two vulnerabilities from the [OWASP listing](http://cwe.mitre.org/top25/#Listing) , them being
- [x] SQL injection
- [x] Input validation

This repo is currently divided into two parts, 
- the vulnerable code (in branch [develop](https://github.com/prodicus/thanos/tree/develop))
- the secure code (in branch [input-validation](https://github.com/prodicus/thanos/tree/input-validation))

I have added some images for context.

**Comment by sinscary** [comment]
@prodicus what's the task for me

**Comment by tasdikrahman** [comment]
Writing test cases is still left out!

I will create an issue and assign it to you then?
