### ISSUE TITLE
Writing test cases 

### ISSUE THREAD

**Issue by tasdikrahman** [prodicus/thanos#5]
Separating the GUI and database-code should be done first, you could test the database code independent of the GUI then. In a test, load in the database code, initialize a database, run queries against it (e.g. try to inject it and verify that it failed) and then destroy the database.

Some references.
- [`unittest`](https://docs.python.org/3/library/unittest.html) would be the module here
- [Ned Batchelder: Getting Started Testing (PyCon US)](https://www.youtube.com/watch?v=FxSsnHeWQBY)
  - [His slides](https://speakerdeck.com/pycon2014/getting-started-testing-by-ned-batchelder)

Some actual examples
- [https://github.com/trobert2/unittest_repo](https://github.com/trobert2/unittest_repo)
- [https://github.com/randy3k/UnitTesting-example](https://github.com/randy3k/UnitTesting-example)

**Comment by sinscary** [comment]
@prodicus  what the hell are you doing?

**Comment by sinscary** [comment]
@prodicus i am on it and hope to complete it on time, i.e, 26th

**Comment by tasdikrahman** [comment]
@sinscary :+1: .

I have written some basic tests in commit https://github.com/prodicus/thanos/commit/de297ba7bc98c3fe27582a2cc00923c41eaa112d

You can add the `tkinter` test cases
